### ISSUE TITLE
后缀表达式递归陷入死循环

### ISSUE THREAD

**Issue by wumacms** [mokong/ExpressionCalculator#1]
用表达式 100-4*5/10 会让后缀表达式计算方法陷入死循环

**Comment by mokong** [comment]
哈哈,感谢提醒,应该是只支持个位数的运算,单个数字超过 10 之后,遍历的地方没有处理.
我之前想着后来优化来的,但是忘记了...
我回头修改下

**Comment by mokong** [comment]
@xuebusi 已更新解决, 可以再试试
